name: Feature request
description: Suggest an improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: input
    id: repo
    attributes:
      label: Target repository
      placeholder: "pii-detector-fr / llm-benchmark-fr / shadow-ai-audit / exahia"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user pain does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What do you want to add/change?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: checkboxes
    id: checklist
    attributes:
      label: Validation
      options:
        - label: I searched existing issues before opening this request.
          required: true
